### ISSUE TITLE
Missing `umi` dependency

### ISSUE THREAD

**Issue by mAAdhaTTah** [scfido/codeHighlighter#1]
```
± |master ✓| → npm start

> prismdemo@1.0.0 start ~/codeHighlighter
> cross-env PORT=3000 BROWSER=none CONTENT_BASE=wwwroot umi dev

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn umi ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prismdemo@1.0.0 start: `cross-env PORT=3000 BROWSER=none CONTENT_BASE=wwwroot umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prismdemo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-07-21T19_33_55_802Z-debug.log
```

**Comment by scfido** [comment]
First execute `npm install -g umi`

**Comment by mAAdhaTTah** [comment]
If you install it as a local dependency for the project, you'll be able to control which version people are using, avoid problems caused by people using different global versions of umi.

**Comment by scfido** [comment]
Unfortunately, the dependency library `umi` referenced by this example, according to the quick start instructions, only has a global installation. If there are local installation documentation for subsequent version updates, I will update this example again.
